import streamlit as st

'## \"Be fearful when others are greedy and'
'## to be greedy only when others are fearful\"'
'### - Warren Buffett'
'Momentum trading is exactly the opposite to one of the most known quote in investment world.'
'While personally I believe momentum trading has it\'s place and can shine if excuted with discipline,'
'It is no doubt much more volatile than traditional buy-and-hold strategy.'
'Analysis of price history just shows past performance and is no guarantee of future results.'
'And it is only meaningful for short-term strategy.'
''
'Future work include adding more custom options for fine tuning strategies and visualizations, adding more different strategies with more indicators, maybe adding larger pool of stocks/ETFs to choose from.'
''
'Special thanks to [yfinance](https://pypi.org/project/yfinance/) for real time market data.'
'The information contained herein does not constitute investment advice and is not warranted to be accurate, complete, or timely.'
'I am not responsible for any damages or losses arising from any use of this information.'
