import streamlit as st

'# ... but in the long run,'
'# it is a weighing machine.\"'
'## - Benjamin Graham'
''
'---'
''
'Momentum trading is the polar opposite to one of the most recognized quotes in the investment world.'
'Although I personally believe that momentum trading can be effective if executed with discipline,'
'it is undoubtedly much more volatile than the traditional buy-and-hold approach. '
'A review of price history is merely an examination of past performance and cannot guarantee future results. '
'And it is only applicable for short-term strategies.'
''
'---'
''
'Made by Zheng Zhong'
'Feel free to [reach out](https://www.linkedin.com/in/zheng-zhong) if you have any questions.'
'Source Code on [Github](https://github.com/zhong-us/backtesting)'
'Future work include adding more custom options for fine tuning strategies and visualizations; adding more strategies with different indicators; adding larger pool of stocks/ETFs to choose from ...'
''
'Special thanks to [yfinance](https://pypi.org/project/yfinance/) for real time market data.'
''
'---'
''
st.caption('The information contained herein does not constitute investment advice and is not warranted to be accurate, complete, or timely.')
st.caption('I am not responsible for any damages or losses arising from any use of this information.')
